analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#94ba33'
    - '#414143'
    - '#b6b6b6'
    - '#929292'
  brandStrength: 0.456081
  lightness: 1
  rhythmicContrast: 0.5
  saturation: 0.5
cta: {}
layout_spectrum: 0
name: Spinark
opengraph: {}
purpose: []
typography_spectrum: 0.803209
