name: Spinark
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: 'Spinark, One Stop Shop for IoT projects'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#94ba33'
    - '#414143'
    - '#b6b6b6'
    - '#929292'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
